name: CI-CD

on:
  push:
    branches: [main]

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/rust-chat
          tags: ${{ github.sha }}, latest

    CD:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3.1.0

        - name: Definindo o context
          uses: azure/aks-set-context@v3
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.K8S_CONFIG }}
        - name: Deploy to Kubernetes cluster
          uses: Azure/k8s-deploy@v4
          with:
            images: VitorLivi/rust-chat:latest
            manifests: |
              k8s/deployment.yaml
